### ISSUE TITLE
Elasticsearch must be provisioned in a VPC.

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#101]

**Comment by kmonihen** [comment]
```
  - id: ELASTICSEARCH_VPC
    message: Elasticsearch domain must be in a VPC
    resource: aws_elasticsearch_domain
    severity: FAILURE
    assertions:
      - key: vpc_options
        op: present
    tags:
      - elasticsearch
```
