### ISSUE TITLE
ElasticSearch must be configured to encrypt traffic between nodes.

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#102]

**Comment by kmonihen** [comment]
```
  - id: ELASTICSEARCH_NODE_TO_NODE_ENCRYPTION
    message: Elasticsearch domain must have encryption at rest
    resource: aws_elasticsearch_domain
    severity: FAILURE
    assertions:
      - key: node_to_node_encryption
        op: present
      - every:
          key: node_to_node_encryption
          expressions:
            - key: enabled
              op: is-true
    tags:
      - elasticsearch
```
