### ISSUE TITLE
ElasticSearch Domains must have encryption at rest

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#103]

**Comment by kmonihen** [comment]
```
  - id: ELASTICSEARCH_ENCRYPTION_REST
    message: Elasticsearch domain must be encrypted at rest
    resource: aws_elasticsearch_domain
    severity: FAILURE
    assertions:
      - key: encrypt_at_rest
        op: present
      - every:
          key: encrypt_at_rest
          expressions:
            - key: enabled
              op: is-true
    tags:
      - elasticsearch
```
