### ISSUE TITLE
Feature: Add Operation for CIDR Calculations

### ISSUE THREAD

**Issue by rmorris1218** [stelligent/config-lint#14]
Add an `is-subnet` operator that can determine whether or not the value is a member of a given network. 

This will be used to allow our Terraform SCA to check security group rules are within RFC1918 ranges.

Example:
```  
...
  - id: SG1
    resource: aws_security_group
    message: Security group should not allow ingress from 0.0.0.0/0
    severity: FAILURE
    assertions:
      - key: "ingress[].cidr_blocks[] | [*]"
        op: is-subnet
        value: "10.0.0.0/8"
...
```

I am happy to implement this. Do you have any reqs for the design? Otherwise I can submit a PR for review. @lhitchon @jeffb4

**Comment by lhitchon** [comment]
I'm happy to review a PR. I'd expect it to include the code, a unit test, and updates to the documentation. An example like the above should be sufficient.
But I would recommend using the 'every' facility for the example since you are dealing with a list of cidr_blocks. Something like this:

```
   assertions:
       - every:
             key: "ingress[].cidr_blocks[]"
             expressions:
                 - key: "@"
                    op: is-subnet
                    value: "10.0.0.0/8"
```

Is also looks like I no longer have write privileges on the repo @jeffb4 
If you add me back, I can approve the PR. Otherwise I'll just review it and let you merge it.
