### ISSUE TITLE
yaml anchors are not respected

### ISSUE THREAD

**Issue by kidbrax** [stelligent/config-lint#141]
When you use a yaml anchor, it causes an error:

`Failed to load rules: error unmarshaling JSON: json: cannot unmarshal string into Go struct field RuleSet.Resources of type assertion.ResourceConfig`

It would be great if we could use anchors to DRY up our rules. For example:

```
---
version: 1
description: Check for JMFE standards in Terraform files
type: Terraform
files:
  - "*.tf"

# resources anchor. reused in rules below
resources: &stage_resources
  - ../../modules/rds
  - ../../modules/snapnlb
  - ../../modules/sqlec2
  - ../../modules/web
  - ../../modules/web80
  - ../../modules/webdmz
  - ../../modules/webnlb
  - ../../modules/wls

rules:
  - id: ALLOWED_SERVICE_LEVEL
    message: "ServiceLevel tag must be Standard or Enhanced"
    category: module
    resources: *stage_resources
    assertions:
      - key: ServiceLevel
        op: in
        value: Standard,Enhanced
        severity: WARNING

  - id: ALLOWED_RECOVERY_LEVEL
    message: "Recovery tag must be Manual, Automated, Partial or Single"
    category: module
    resources: *stage_resources
    assertions:
      - key: Recovery
        op: in
        value: Manual,Automated,Partial,Single
        severity: FAILURE

  - id: ALLOWED_DEPLOYMENT_COLOR
    message: "DeploymentColor must be blue, green or black"
    category: module
    resources: *stage_resources
    assertions:
      - key: DeploymentColor
        op: in
        value: blue,green,black
        severity: FAILURE

```
