### ISSUE TITLE
Containers array searching

### ISSUE THREAD

**Issue by namloc2001** [stelligent/config-lint#153]
Hi, do you please know the syntax/have an example of checking for all instances in an array for K8s yaml?

I'm trying to see if all containers in a deployment have declared some specified securitycontexts:
```
  - id: DEPLOYMENT_CONTAINER_SECURITY_CONTEXT
    severity: NON_COMPLIANT
    message: Deployment container should set securityContexts
    resource: Deployment
    assertions:
      - key: spec.template.spec.containers[].securityContext.runAsNonRoot
        op: eq
        value: true
      - key: spec.template.spec.containers[].securityContext.readOnlyRootFilesystem
        op: eq
        value: true
    tags:
      - deployment
      - security
```
If I put a "0" in the [] it will correctly identify against the first container.

Thanks,

Matt

**Comment by phelewski** [comment]
@namloc2001 This seems like the perfect use case for the [every](https://github.com/stelligent/config-lint/blob/master/docs/operations.md#every) operator to go through all of the containers. Without seeing what you are working with I would think something like this might get the results you are looking for. Also note that there is an operator to check for `true`, I've used it in the example below.

``` yaml
  - id: DEPLOYMENT_CONTAINER_SECURITY_CONTEXT
    severity: NON_COMPLIANT
    message: Deployment container should set securityContexts
    resource: Deployment
    assertions:
      - every:
        key: spec.template.spec.containers[]
        expressions:
          - key: securityContext.runAsNonRoot
            op: is-true
          - key: securityContext.readOnlyRootFilesystem
            op: is-true
    tags:
      - deployment
      - security
```

**Comment by namloc2001** [comment]
Ooo I like that. So I'm using:
```
  - id: DEPLOYMENT_CONTAINER_SECURITY_CONTEXT
    severity: NON_COMPLIANT
    message: Deployment containers should set securityContexts
    resource: Deployment
    assertions:
      - every:
        key: spec.template.spec.containers[]
        expressions:
        - key: securityContext.runAsNonRoot
          op: is-true
        - key: securityContext.readOnlyRootFilesystem
          op: is-true
    tags:
      - deployment
      - security
```

to check this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        readOnlyRootFilesystem: true
      restartPolicy: Always
      serviceAccountName: my-app
      containers:
      - name: my-app
        image: "my_image:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        securityContext:
          readOnlyRootFilesystem: true
```
But I'm getting:
```
  {
    "AssertionMessage": "unknown op ",
    "Category": "",
    "CreatedAt": "2020-03-05T17:33:12Z",
    "Filename": "/foobar/configs/deployment.yaml",
    "LineNumber": 0,
    "ResourceID": "openvas",
    "ResourceType": "Deployment",
    "RuleID": "DEPLOYMENT_CONTAINER_SECURITY_CONTEXT",
    "RuleMessage": "Deployment containers should set securityContexts",
    "Status": "NON_COMPLIANT"
  }
```

Thanks,

Matt

**Comment by phelewski** [comment]
@namloc2001 my apologies, the formatting from my previous comment didn't paste correctly. I've fixed it for now, but for future reference the tabbing/spacing is important for the operators. 

From:
``` yaml
    assertions:
      - every:
        key: spec.template.spec.containers[]
        expressions:
          - key: securityContext.runAsNonRoot
            op: is-true
```

To:
``` yaml
    assertions:
      - every:
          key: spec.template.spec.containers[]
          expressions:
            - key: securityContext.runAsNonRoot
              op: is-true
```

**Comment by namloc2001** [comment]
Thanks. So I'm using this rule:
```
  - id: DEPLOYMENT_CONTAINER_SECURITY_CONTEXT
    severity: NON_COMPLIANT
    message: Deployment containers should set securityContexts
    resource: Deployment
    assertions:
      - every:
          key: spec.template.spec.containers
          expressions:
            - key: securityContext.runAsNonRoot
              op: is-true
            - key: securityContext.readOnlyRootFilesystem
              op: is-true
    tags:
      - deployment
      - security
```

Against this config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        readOnlyRootFilesystem: true
      restartPolicy: Always
      serviceAccountName: my-app
      containers:
      - name: my-app
        image: "my_image:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        securityContext:
          readOnlyRootFilesystem: true
```
Which should detect that 'runAsNonRoot' is missing and so rule violation occurs. This now happens, but AssertionMessage is a little interesting/crazy/TMI:
```
"AssertionMessage": "Every expression fails: And expression fails: securityContext.runAsNonRoot should be 'true', not ''",
```
