### ISSUE TITLE
AWS Terraform rule REDSHIFT_CLUSTER_PARAMETER_GROUP_REQUIRE_SSL fails when more than one parameter group is specified

### ISSUE THREAD

**Issue by kmonihen** [stelligent/config-lint#176]
The AWS Terraform rule REDSHIFT_CLUSTER_PARAMETER_GROUP_REQUIRE_SSL will fail when more than one parameter group is specified.

Example:
```
resource "aws_redshift_parameter_group" "require_ssl_set_to_true_multi_param" {
  name   = "foobar"
  family = "redshift-1.0"

  parameter {
    name  = "require_ssl"
    value = "true"
  }
  parameter {
    name  = "query_group"
    value = "example"
  }
  parameter {
    name  = "enable_user_activity_logging"
    value = "true"
  }
}
```

**Comment by kmonihen** [comment]
The rule as it's currently written doesn't account for multiple parameter keys.

```
  - id: REDSHIFT_CLUSTER_PARAMETER_GROUP_REQUIRE_SSL
    message: RedshiftCluster Parameter Group should set require_ssl to true
    resource: aws_redshift_parameter_group
    severity: WARNING
    assertions:
      - key: parameter
        op: present
      - every:
          key: parameter
          expressions:
            - key: name
              op: eq
              value: require_ssl
            - key: value
              op: is-true
```

**Comment by kmonihen** [comment]
Looking at this closer, if multiple keys are present they are represented as a list.

```
require_ssl_set_to_true_multi_param (aws_redshift_parameter_group): {
  "__name__": "require_ssl_set_to_true_multi_param",
  "__type__": "aws_redshift_parameter_group",
  "family": "redshift-1.0",
  "name": "foobar",
  "parameter": [
    {
      "name": "require_ssl",
      "value": "true"
    },
    {
      "name": "query_group",
      "value": "example"
    },
    {
      "name": "enable_user_activity_logging",
      "value": "true"
    }
  ]
}
```

**Comment by kmonihen** [comment]
```
  - id: REDSHIFT_CLUSTER_PARAMETER_GROUP_REQUIRE_SSL
    message: RedshiftCluster Parameter Group should set require_ssl to true
    resource: aws_redshift_parameter_group
    severity: WARNING
    assertions:
      - exactly-one:
          key: parameter
          expressions:
            - key: name
              op: eq
              value: require_ssl
            - key: value
              op: is-true
```
