### ISSUE TITLE
Allow multiple resources for each rule

### ISSUE THREAD

**Issue by rmorris1218** [stelligent/config-lint#2]
Allow a rule to apply to multiple resources, defined as a list.

Example:

```
  - id: UTAN_VALID_REGEX
    resources: 
        - aws_dynamodb_table
        - aws_instance
    message: make sure that UTAN is a valid regex
    severity: WARNING
    assertions: 
      - key: tags[0].utan
        op: regex
        value: "^[0-9]{5}$"
```
