### ISSUE TITLE
tf12 errors on parameter list format

### ISSUE THREAD

**Issue by twellspring** [stelligent/config-lint#207]
For the tf12 parser the block syntax works as expected:
```
  parameter {
        name  = "tls"
        value = "enabled"
      }
  parameter  {
        name = "audit_logs"
        value = "enabled"
      }
```

But the list of objects returns a warning/failure condition for the same rule
```
  parameter   = 
    [{
        name  = "tls"
        value = "enabled"
      },
      {
        name = "audit_logs"
        value = "enabled"
      }]
```

Per https://www.terraform.io/docs/configuration/attr-as-blocks.html this syntax is not recommended, but is still supported.

Assertion that works for blocks and fails for list of objects
```
    assertions:
      - some:
          key: parameter
          expressions:
            - and:
              - key: name
                op: eq
                value: tls
              - key: value
                op: eq
                value: enabled
```
