### ISSUE TITLE
Add max-host-count Operation

### ISSUE THREAD

**Issue by rmorris1218** [stelligent/config-lint#21]
Add a `max-host-count` operations. This would be especially helpful in assessing CIDR blocks in configuration.

For example:

```
...
  - id: MAX_HOSTS_EXPOSED_PER_RULE
    message: All security group rules must expose less than 1016 hosts
    severity: FAILURE
    resource: aws_security_group_rule
    assertions:
      - every:
        key: "cidr_blocks"
        expressions:
          - key: "@"
            op: max-host-count
            value: 1016
...
```
