### ISSUE TITLE
Incorrect rules are skipped without mention, giving the impression all is well

### ISSUE THREAD

**Issue by fliphess** [stelligent/config-lint#218]
Hey :) Thanks for writing this utility.

I have some questions regarding missing keys or checks that are suppose to fail but dont.

I have the following yaml:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: some-chart
  namespace: default
  annotations:
    fluxcd.io/automated: false
```

When I on purpose remove a few chars so that the assertion is supposed to fail:

```
- id: CHECK_HELMRELEASE
  severity: FAILURE
  message: Check validity for helmrelease
  resource: "HelmRelease"
  assertions:
  - key: metadata
    op: has-properties
    value: name,namespace,annotat
```

.... The check still succeeds. 

Is this intended behaviour? It looks like a regex is used or a string in string comparison where the full key should be checked instead.
