### ISSUE TITLE
Allow comparison of multiple values

### ISSUE THREAD

**Issue by fliphess** [stelligent/config-lint#219]
Hi! 

This is a feature request: 

I'd love to be able to make a comparison between multiple keys in a kubernetes file. 
For example: ensure that multiple values are equal or use jmespath in both key and values:

```
  assertions:
  - key: spec.values[].image.tag
    op: eq
    value_from: 
      key: spec.values.mainVersion
```

or 

```
  assertions:
  - key: spec.values.somevalue
    op: eq
    value_from: 
      key: spec.values.some_other_value
```
