### ISSUE TITLE
How do I integrate configlint-docker with gitlab-ci

### ISSUE THREAD

**Issue by gr8Adakron** [stelligent/config-lint#221]
Hey I have been trying to setup configlint testing for Kubernetes configuration via gitlab ci. I couldnt find much documentation on it. Using docker I am able to get configlint work in my local using the below command:

```
docker run -v $(pwd):/tmp/ stelligent/config-lint -rules /tmp/ruleset.yaml /tmp/tdir/
```

And my .gitlab-ci.yaml file is as mentioned below:

```
image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/

stages:
  - test

test:
  stage: test
  image: stelligent/config-lint
  before_script:
  - docker info
  script:
    - echo "Executing testing"
    - config-lint -rules ruleset.yaml tdir/
 

```

Which return the following error:

```
*********
Pulling docker image stelligent/config-lint ...
Using docker image sha256:de3caf50cb69734c5174fd824a6704e1b71fb892320f8a975645364071bebd32 for stelligent/config-lint ...
Preparing environment
Running on runner-kmxtw95l-project-257-concurrent-0 via runner-2...
Getting source from Git repository
00:02
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/code/k8s/human-workflow/tasky/.git/
Checking out 5c8f3458 as configlint-testing...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
ERROR: Job failed: exit code 255

```

Any help will be appreciated, thanks.

**Comment by gr8Adakron** [comment]
@kidbrax any help

**Comment by aviadlevy** [comment]
You can use [linux installation](https://stelligent.github.io/config-lint/#/install?id=linux) instead  
This is worked for  me:  
```yaml
test:
  stage: test
  image: alpine
  script:
    - apk add curl
    - curl -L https://github.com/stelligent/config-lint/releases/download/v1.6.0/config-lint_Linux_x86_64.tar.gz | tar xz -C /usr/local/bin config-lint
    - chmod +rx /usr/local/bin/config-lint
    - config-lint -rules ruleset.yaml tdir/
```
