### ISSUE TITLE
Rule runs on everything when it should not.

### ISSUE THREAD

**Issue by ekristen** [stelligent/config-lint#226]
Taken from the docs, when run in verbose mode, this appears to run on ever single resource when it should only run against variables. The same happens when category is module, data, and resource.

```
---
version: 1
description: Make sure Terraform top level blocks follow best practices.
type: Terraform
files:
  - "*.tf"
rules:
  - id: TF_VARIABLE_NAMING_CONVENTION
    message: "Terraform variable block name should match the naming convention. Name should be: not more 64 chars, starts with letter, doesn't have dash, and ends with letter or number"
    severity: FAILURE
    category: variable
    assertions:
      - key: __name__
        op: regex
        value: "^[a-z][a-z0-9_]{0,62}[a-z0-9]$"
```
