### ISSUE TITLE
Elastic Transcoder Pipeline must be encrypted.

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#90]

**Comment by kmonihen** [comment]
```
  - id: TRANSCODER_REQUIRE_ENCRYPTION
    message: Elastictranscoder pipeline requires encryption
    resource: aws_elastictranscoder_pipeline
    severity: FAILURE
    assertions:
      - key: aws_kms_key_arn
        op: present
    tags:
      - elastictranscoder
```
