### ISSUE TITLE
OpsWorks application should utilize SSL

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#91]

**Comment by kmonihen** [comment]
```
 - id: OPSWORKS_APP_SSL
    message: OpsWorks Applications must use SSL
    resource: aws_opsworks_application
    severity: FAILURE
    assertions:
      - key: enable_ssl
        op: is-true
    tags:
      - opsworks
```
