### ISSUE TITLE
SQS Queue should contain the kms_master_key_id and kms_data_key_reuse_period_seconds properties

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#92]

**Comment by kmonihen** [comment]
```
  - id: SQS_QUEUE_ENCRYPTION
    message: SQSQueue should use encryption and define a reuse period
    resource: aws_sqs_queue
    severity: FAILURE
    assertions:
      - key: "@"
        op: has-properties
        value: kms_master_key_id, kms_data_key_reuse_period_seconds
    tags:
      - sqs
```
