### ISSUE TITLE
CloudFront distribution should be HTTPS only or use Origin Access Identity (OAI)

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#93]

**Comment by kmonihen** [comment]
```
  - id: CLOUDFRONT_DISTRIBUTION_ORIGIN_POLICY
    message: CloudFront Distribution should use OAI or origin_protocol_policy should be https-only
    resource: aws_cloudfront_distribution
    severity: FAILURE
    assertions:
      - or:
        - key: "origin[].s3_origin_config[].origin_access_identity"
          op: present
        - or:
          - key: "origin[].custom_origin_config"
            op: absent
          - key: "origin[].custom_origin_config[].origin_protocol_policy"
            op: contains
            value: https-only
    tags:
      - cloudfront
```
