### ISSUE TITLE
DocumentDB storage encryption must be enabled

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#98]

**Comment by kmonihen** [comment]
```
  - id: DOCUMENTDB_STORAGE_ENCRYPTION
    message: DocumentDB should have storage encryption enabled
    resource: aws_docdb_cluster
    severity: FAILURE
    assertions:
      - key: storage_encrypted
        op: is-true
    tags:
      - documentdb
```
