### ISSUE TITLE
DocumentDB audit logs must be enabled

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#99]

**Comment by kmonihen** [comment]
```
  - id: DOCUMENTDB_AUDIT_LOGS
    message: DocumentDB should have audit logging enabled
    resource: aws_docdb_cluster
    severity: FAILURE
    assertions:
      - key: enabled_cloudwatch_logs_exports
        op: contains
        value: "audit"
    tags:
      - documentdb
```
